clear all;

load('net-snapshot.mat') % enter path to net-snapshot here. If necessary rename your saved network to net

test_image_dir = '/home/jens/Schreibtisch/machine_vision/uebung/git_jens/uebung_7/Images_scaled';
testImages = imageDatastore(test_image_dir,...
    'IncludeSubfolders',true,...
    'LabelSource','foldernames');
numClasses = numel(categories(testImages.Labels));

keySet = 0:42;
valueSet = {...
    'Speed limit 20', ...
    'Speed limit 30', ...
    'Speed limit 50', ...
    'Speed limit 60', ...
    'Speed limit 70', ...
    'Speed limit 80', ...
    'Restriction ends 80', ...
    'Speed limit 100', ...
    'Speed limit 120', ...
    'No overtaking', ...
    'No overtaking Trucks', ...
    'Priority at next intersection', ...
    'Priority road ', ...
    'Give Way', ...
    'Stop', ...
    'No traffic both ways', ...
    'No trucks', ...
    'No entry', ...
    '(Highway to the) Dangerzone', ...
    'Bend left (danger)', ...
    'Bend right (danger)', ...
    'Bend (danger)', ...
    'Uneven road', ...
    'Slippery road', ...
    'Road narrows', ...
    'Construction', ...
    'Traffic signal', ...
    'Pedestrian crossing', ...
    'School crossing', ...
    'Cycles crossing', ...
    'Snow', ...
    'Animals', ...
    'Restrictions end', ...
    'Go right (mandatory)', ...
    'Go left (mandatory)', ...
    'Go straight (mandatory)', ...
    'Go right or straight (mandatory)', ...
    'Go left or straight (mandatory)', ...
    'Keep right (mandatory)', ...
    'Keep left (mandatory)', ...
    'Roundabout', ...
    'Restriction ends (overtaking)', ...
    'Restriction ends trucks (overtaking)', ...
    };
map = containers.Map(keySet,valueSet);

idx = randi([0, 12000], 5);
figure(1);
for i = 1:numel(idx)
    subplot(5,5,i)
    label = classify(net, readimage(testImages,idx(i)));
    I = readimage(testImages,idx(i));
    imshow(I)
    title(map(int8(label)-1))
end

figure(2);
for i = 1:96
    subtightplot(10,10,i)
    imagesc(net.Layers(2,1).Weights(:,:,1,i));
    axis off;
end

figure(3);
for i = 1:96
    subtightplot(10,10,i)
    imagesc(net.Layers(6,1).Weights(:,:,1,i));
    axis off;
end

figure(4);
for i = 1:96
    subtightplot(10,10,i)
    imagesc(net.Layers(14,1).Weights(:,:,1,i));
    axis off;
end
